.github/workflows/reusable-release.yaml
README.md

Signed-off-by: Ramiz Polic <rpolic@cisco.com>

fix: release latest version for helm chart

---

server/lib/schema_web/templates/layout/app.html.eex

fix: update navbar links to point to the homepage

---

CONTRIBUTING.md
schema/dictionary.json
schema/metaschema/common-event-object.schema.json
schema/metaschema/dictionary.schema.json
schema/metaschema/event.schema.json
schema/metaschema/extension.schema.json
schema/metaschema/profile.schema.json
schema/metaschema/references.schema.json
schema/objects/acp.json
schema/objects/agent_manifest_ref.json
schema/objects/interrupts.json
schema/objects/security_scheme.json
schema/templates/class_name.json
server/lib/schema.ex
server/lib/schema/cache.ex
server/lib/schema/generator.ex
server/lib/schema/graph.ex
server/lib/schema/helper.ex
server/lib/schema/translator.ex
server/lib/schema_web/controllers/page_controller.ex
server/lib/schema_web/controllers/schema_controller.ex
server/lib/schema_web/templates/page/profiles.html.eex
server/test/test_schema/dictionary.json
server/test/test_schema/extensions/rpg/classes/alpha_(patch).json

Updated link formats and removed event mentions.

fix: update link formats

---

server/lib/schema_web/templates/layout/app.html.eex

Terms & Conditions and Privacy Policy

feat: add links to footer

---

schema/features/observability/formats.json
schema/features/runtime/manifest.json
schema/objects/manifest_data.json
schema/objects/observability_data.json
server/lib/schema.ex
server/lib/schema/cache.ex
server/lib/schema/generator.ex
server/lib/schema/json_schema.ex
server/lib/schema/types.ex

Ensured to display and generate features/extensions in the expected format.
- extension-specific data object can be specified for every feature and it is displayed on the UI correctly
- correct name and version is generated both in the description on the UI and in the generated JSON
- some small fixes and cleanups
```json
{
"name":"carroll devil courier",
"version":"v0.1.0",
"extensions":[
{
"data":{
"acp":{
"input":"membership",
"output":"operator",
"config":"expand",
"capabilities":{
"streaming":{
"result_streaming":false
}
}
},
"agent_deployment":{
"dependencies":[
{
"name":"resulted never cooking",
"version":"v0.1.0"
}
]
}
},
"name":"oasf.agntcy.org/feature/runtime/manifest",
"version":"v0.1.0"
},
{
"data":{
"communication_protocols":[
"Otel_OTP_v1",
"gRPC"
], …
```

feat: extension generator

---

schema/main_domains.json

fix(schema): fix domain category numbers

---

server/lib/schema_web/views/page_view.ex

Add missing check on enum attributes (whether to make them visible on the UI or not).

fix(server): add missing check on enum attributes

---

schema/base_class.json
schema/dictionary.json
schema/features/base_feature.json
schema/objects/agent.json
schema/objects/env_var.json
schema/profiles/datetime.json
server/lib/schema/cache.ex
server/lib/schema/generator.ex
server/lib/schema/types.ex
server/lib/schema_web/controllers/schema_controller.ex
server/test/test_schema/profiles/datetime.json

Synchronize data models with agent directory.

feat: update agent object and base classes

---

schema/dictionary.json
schema/metaschema/dictionary-attribute.schema.json
server/lib/schema/translator.ex
server/lib/schema/types.ex
server/lib/schema/validator.ex
server/lib/schema_web/controllers/page_controller.ex
server/lib/schema_web/templates/page/class.html.eex
server/lib/schema_web/views/page_view.ex

Implemented proper translation and validation for attributes of class type (currently only used in the `agent` object)

feat: validation and translation for `class_t`

---

server/lib/schema/generator.ex

The sample generator did not respect constraints, e.g. it included every attribute in the the generated object listed in the `just_one` constraint, this PR fixes that. 
Fixes #128

fix: sample generator to respect constraints

---

schema/dictionary.json
schema/objects/locator.json
schema/objects/signature.json

Fixed schema v0.3.1 by adding signature object and fixing `python-package` locator enum.

fix: schema

---

proto/README.md
proto/objects/v3/extension.proto
proto/objects/v3/locator.proto
proto/objects/v3/record.proto
proto/objects/v3/signature.proto
proto/objects/v3/skill.proto
schema/dictionary.json
schema/objects/extension_data.json
schema/objects/llm_model_data.json
schema/objects/llm_prompt_data.json
schema/objects/locator.json
schema/objects/mcp_server_data.json
schema/objects/record.json
schema/objects/signature.json
server/lib/schema_web/templates/layout/app.html.eex

Fixes #190 without changing previously released content. 
Creates v3 proto files.

feat: renamed agent_record to record

---

schema/version.json
server/lib/schema_web/router.ex
server/mix.exs

Bumps versions, getting ready for releasing v0.5.0

chore: bump versions

---

docker-bake.hcl
server/Dockerfile

build: improve Dockerfile

---

.github/workflows/ci.yaml

fix: ci workflow GHA

---

server/lib/schema/types.ex
server/lib/schema_web/controllers/schema_controller.ex

Revert "fix: rename remaining web links"

---

server/.gitignore
server/config/test.exs
server/lib/schema.ex
server/lib/schema/cache.ex
server/lib/schema/json_reader.ex
server/lib/schema/repo.ex
server/lib/schema/translator.ex
server/lib/schema/utils.ex
server/lib/schema/validator.ex
server/lib/schema_web/controllers/page_controller.ex
server/lib/schema_web/controllers/schema_controller.ex
server/lib/schema_web/views/page_view.ex
server/lib/schemas.ex
server/test/schema/compilation_test.exs

Notable changes:
- semver validator for OASF schema version
- backend for better presenting enum siblings
- added schema compilation test
- sort attributes by descoped key
Fixes #221

feat: update server with upstream changes

---

.github/ISSUE_TEMPLATE/bug_report.yml

fix: versions in bug report template

---

server/lib/schema/generator.ex
server/lib/schema/json_schema.ex
server/lib/schema/validator.ex

Minor validator and generator fixes.

fix(server): minor generator and validator issues

---

server/lib/schema.ex
server/lib/schema/cache.ex
server/lib/schema/json_schema.ex
server/lib/schema/repo.ex
server/lib/schema/translator.ex
server/lib/schema/types.ex
server/lib/schema/utils.ex
server/lib/schema/validator.ex

feat(server): validator adjustments

---

server/lib/schema/validator.ex

fix(server): error when input is not a map in validator

---

README.md
schema/objects/signature.json
schema/references/agntcy_observability/README.md
server/lib/schema/generator.ex
server/lib/schema/json_schema.ex
server/lib/schema/validator.ex
server/lib/schema_web/router.ex
server/lib/schema_web/templates/layout/app.html.eex

Backport some validator, generator bug fixes and backward-compatible fix for the `record` object to the v0.7.0 version of the schema&server.

fix: validator, generator, signature object

---

server/lib/schema/graph.ex
server/lib/schema_web/controllers/page_controller.ex
server/lib/schema_web/templates/layout/app.html.eex
server/lib/schema_web/templates/page/class.html.eex
server/lib/schema_web/templates/page/class_graph.html.eex
server/lib/schema_web/templates/page/classes.html.eex
server/lib/schema_web/templates/page/data_types.html.eex
server/lib/schema_web/templates/page/dictionary.html.eex
server/lib/schema_web/templates/page/index.html.eex
server/lib/schema_web/templates/page/object.html.eex
server/lib/schema_web/templates/page/objects.html.eex
server/lib/schema_web/templates/page/profile.html.eex
server/lib/schema_web/templates/page/profiles.html.eex
server/lib/schema_web/views/page_view.ex
server/priv/static/css/components.css
server/priv/static/css/layout.css
server/priv/static/js/app.js
server/priv/static/js/profiles.js

- improved class and object pages
- improved graph view (loading a class also display its subclasses)
Closes #112 
Further improves #118 
| Before        | After         |
| ------------- | ------------- |
| <img width="1428" height="907" alt="Screenshot 2025-09-24 at 16 53 24" src="https://github.com/user-attachments/assets/71f188f8-bcd5-48f4-bff6-6169eef376be" /> | <img width="1428" height="907" alt="Screenshot 2025-09-24 at 16 53 53" src="https://github.com/user-attachments/assets/d35160d0-3889-4644-90c8-8a9db467de37" /> |
| <img width="1428" height="907" alt="Screenshot 2025-09-24 at 16 53 31" src="https://github.com/user-attachments/assets/ea2aa04e-3d36-4b23-b3b7-ac5abe5f958d" /> | <img width="1428" height="907" alt="Screenshot 2025-09-24 at 16 53 59" …

feat: entity and graph UI improvements

---

CONTRIBUTING.md
README.md
schema/domain_categories.json
schema/module_categories.json
schema/skill_categories.json
server/lib/schema.ex
server/lib/schema/cache.ex
server/lib/schema/repo.ex
server/lib/schema_web/controllers/page_controller.ex
server/lib/schema_web/controllers/schema_controller.ex
server/lib/schema_web/router.ex
server/lib/schema_web/templates/layout/app.html.eex
server/lib/schema_web/templates/page/class.html.eex
test/schema/schema_test.go

Renamed main_skills -> skill_categories etc. and bumped the API version. 
This is a breaking change as the name of some endpoints changed but better do it now than later!
Fixes #322

refactor(schema, server)!: class categories

---

server/lib/schema/cache.ex
server/lib/schema/generator.ex

fix: don't include deprecated classes in sample
