agntcy/oasf

.github/workflows/ci.yaml
.github/workflows/reusable-build.yaml
.github/workflows/reusable-release.yaml
.github/workflows/reusable-test.yaml
Taskfile.yml

Do not release images in non-release workflow runs. Instead use Github Action artifacts to share images between jobs

fix: use GA artifacts in CICD pipeline

---

schema/domains/trust_and_safety/content_moderation.json
schema/domains/trust_and_safety/data_privacy.json
schema/domains/trust_and_safety/fraud_prevention.json
schema/domains/trust_and_safety/online_safety.json
schema/domains/trust_and_safety/risk_management.json
schema/domains/trust_and_safety/trust_and_safety.json
schema/features/evaluation/evaluation.json
schema/features/evaluation/trust_and_safety.json
schema/main_domains.json
schema/skills/nlp/ethical_interaction/content_moderation.json
server/lib/schema.ex
server/lib/schema/cache.ex
server/lib/schema/repo.ex
server/lib/schema/utils.ex
server/lib/schema_web/controllers/page_controller.ex
server/lib/schema_web/controllers/schema_controller.ex
server/lib/schema_web/router.ex
server/lib/schema_web/templates/layout/app.html.eex
server/lib/schema_web/templates/page/category.html.eex
server/lib/schema_web/templates/page/class.html.eex
server/lib/schema_web/views/page_view.ex

1. Separated skills from classes and main_skills from categories in the cache, routes and controllers:
- now the generic classes and categories objects and endpoints respond with all the classes and all the categories
- the skills and main_skills endpoints respond only with the skill classes and skill categories
2. Refactored some parts along the way to have fewer code duplications.
3. Fixed some issues in the schema and ensured there are no duplicate class names

feat: separate skills from classes

---

schema/dictionary.json
schema/objects/insights.json
schema/objects/melt_telemetry.json
schema/objects/metric.json
schema/objects/metrics.json
schema/objects/observability.json
schema/objects/performance.json
schema/objects/sustainability.json

Adds initial agent and multi-agentic application observability schema to the OASF. 
Signed-off-by: Laszlo Gecse [lgecse@cisco.com](mailto:lgecse@cisco.com)

feat: add observability to the schema

---

schema/dictionary.json
schema/metaschema/dictionary-attribute.schema.json
schema/objects/agent_deployment.json
schema/objects/agentic_framework_config.json
schema/objects/deployment_option.json
schema/objects/docker_deployment.json
schema/objects/langgraph_config.json
schema/objects/llamaindex_config.json
schema/objects/remote_service_deployment.json
schema/objects/source_code_deployment.json
server/lib/schema/generator.ex
server/lib/schema/utils.ex
server/lib/schema_web/templates/page/object.html.eex
server/lib/schema_web/views/page_view.ex

Implemented handling object enums on the UI and in the JSON generator. Also refactored similar code regarding class type to use the same logic.
Object enums are useful if only a limited scope of object are valid as a class/object attribute, that is, if the only valid choices are objects extending one specific object. This can be marked by the newly introduced `is_enum` field that can be aded to an attribute. Both in case of a `class_t` or `object_t`, the generator will pick an object/class that extends from the provided object/class. Example generated `Agent deployment` object (both `deployment_option` and `framework_config` are object enums):
On the UI, an object page displays a new table is displayed with the children of the object, if it has any. Also there is a new `Options` section …

feat: object enum

---

server/lib/schema/generator.ex

It should always generate at least 1 element.

fix(server): array generation

---

schema/objects/agntcy_observability_schema.json

Use the references property instead of the description for the schema link.

fix(schema): Agntcy observability schema reference

---

schema/dictionary.json
server/lib/schema/validator.ex
server/lib/schema_web/views/page_view.ex

Modify `annotations` to use `string_map_t`, add validator for the type.
+1 quick fix for type formatting on the UI

feat: implement string map type

---

server/lib/schema/generator.ex

Implement generating a valid map with a random number of string keys and values, following up #103.

feat: implement generator for string_map_t type

---

Taskfile.yml

Fixes docker image version mismatch that causes local deployment failure during `task up`.
- `docker buildx bake` builds images with `latest` tag by default
- `values-test.yaml` expects images with versioned tags (e.g., `v0.3.1`)
- This mismatch causes "image not present locally" errors during Kind cluster deployment
Modified `Taskfile.yml` to:
- Dynamically read version from `schema/version.json`
- Set `IMAGE_TAG` environment variable with proper `v` prefix during build
- Ensure consistent tagging between build and deployment processes
- **Taskfile.yml**: Added `SCHEMA_VERSION` variable and dynamic `IMAGE_TAG` setting in `build:images` task
Verified `task build:images` creates correctly tagged image  
Verified `task up` deploys successfully without manual intervention  
Tested version …

fix: resolve docker image version mismatch in local deployment

---

schema/dictionary.json
schema/features/runtime/a2a.json
schema/features/runtime/mcp_server.json
schema/features/runtime/model.json
schema/features/runtime/prompt.json
schema/objects/a2a_card_data.json
schema/objects/llm_model.json
schema/objects/llm_model_data.json
schema/objects/llm_prompt.json
schema/objects/llm_prompt_data.json
schema/objects/mcp_server_configurations.json
schema/objects/mcp_server_data.json
schema/objects/mcp_server_input.json

Added new features under `runtime` category:
Attributes are not a 100% match until https://github.com/agntcy/oasf/issues/150 is completed.
Closes #130 
Closes #131 
Closes #132

feat(schema): add LLM/Prompt/A2A/MCP feature extensions

---

README.md
Taskfile.yml
install/charts/oasf/templates/ingress/ingress-api.yaml
install/charts/oasf/templates/ingress/ingress-export.yaml
install/charts/oasf/templates/ingress/ingress-sample.yaml
install/charts/oasf/templates/ingress/ingress-schema.yaml
install/charts/oasf/values-test.yaml

- reverted #142 in favor of using the `latest` tag in the `values-test.yaml` because that implementation prevented overwriting the image tag (e.g. `IMAGE_TAG=v0.3.3 task build:images`, also it is better to use the `latest` tag for development than overwriting an official release
- added default ingress paths to the helm templates so trying out the endpoints work on the Swagger UI 
Still fixes #141

fix: local dev env

---

schema/metaschema/categories.schema.json
server/lib/schema.ex
server/lib/schema/cache.ex
server/lib/schema/generator.ex
server/lib/schema/repo.ex
server/lib/schema/translator.ex
server/lib/schema/types.ex
server/lib/schema/utils.ex
server/lib/schema/validator.ex
server/lib/schema_web/controllers/schema_controller.ex
server/lib/schema_web/views/page_view.ex

Removed general classes, categories maps (where all the classes, categories were merged together from all class families) from cache and all references.
Bonus: references to classes are also fixed on the Dictionary, Objects and Profiles page.
Fixes #158

feat: remove general classes, categories

---

server/lib/schema/generator.ex

The sample generator failed on the agent record, as it used the wrong class function to generate sample skills and features.

fix: class enum sample generator

---

server/lib/schema/cache.ex
server/lib/schema/graph.ex
server/lib/schema/json_schema.ex
server/lib/schema/profiles.ex
server/lib/schema/repo.ex
server/lib/schema/utils.ex
server/lib/schema_web/controllers/schema_controller.ex

Fixed the json draft-07 schema generator, so it handles class types and enum entities. 
- In case of an enum entity it lists the options them in a `oneOf` list
- In case of the record's `extension` attribute it only validates against the OASF features if the name matches with one of them. 
- In case of skills it only accepts skills from OASF.
- object definitions are grouped by object/class family
To try it out online:
1. Visit https://www.jsonschemavalidator.net
2. Navigate to a class/object on OASF UI, and generate the json schema (top right corner, `Schemas` -> `JSON Schema`), paste it into the left pane of the online validator
3. Generate a sample (top right corner, `Schemas` -> `Sample`) and paste it into the right pane of the online validator
4. It should be valid. Try and make it …

fix: json schema generator

---

CONTRIBUTING.md
README.md
proto/README.md
proto/objects/v1/skill.proto
proto/objects/v2/extension.proto
proto/objects/v2/skill.proto
proto/objects/v3/extension.proto
proto/objects/v3/skill.proto
schema/features/base_feature.json
schema/metaschema/attribute.schema.json
schema/metaschema/categories.schema.json
schema/metaschema/class.schema.json
schema/metaschema/common-class-object.schema.json
schema/metaschema/deprecated.schema.json
schema/metaschema/dictionary-attribute.schema.json
schema/metaschema/dictionary.schema.json
schema/metaschema/enum.schema.json
schema/metaschema/extension.schema.json
schema/metaschema/object.schema.json
schema/metaschema/profile.schema.json
schema/metaschema/references.schema.json
schema/metaschema/semver.schema.json
server/lib/schema/json_schema.ex
server/lib/schema/types.ex
server/lib/schema_web/controllers/schema_controller.ex

This PR updates the OASF links due to migration to the new domain under [schema.oasf.outshift.com](https://schema.oasf.outshift.com).

fix: update post-migration OASF web links

---

server/lib/schema/cache.ex
server/lib/schema/generator.ex
server/lib/schema/json_schema.ex
server/lib/schema/utils.ex
server/lib/schema_web/views/page_view.ex

The schema generator fix introduced a regression: hidden classes were appearing on the UI, because to find the children classes required to include them in the regular skills/domains/features/objects maps.
Now only `all_*` maps are being used to find children so hidden classes/objects can be removed from regular maps so they are not appearing on the UI.
Fixes #219

fix: hidden classes on the UI

---

.github/workflows/ci.yaml

Fixed a regression in the ci.yaml file that made it invalid.
Fixes #222

ci: fix Helm release tag calculation

---

server/lib/schema/cache.ex
server/lib/schema/generator.ex
server/lib/schema/json_schema.ex
server/lib/schema/translator.ex
server/lib/schema/types.ex
server/lib/schema/validator.ex
server/lib/schema_web/controllers/schema_controller.ex
server/lib/schema_web/views/page_view.ex
server/priv/static/css/tables.css

Instead of URIs, use class names unique within the current OASF session containing the class hierarchy, so instead of `schema.oasf.agntcy.org/skills/contextual_comprehension` it will be `natural_language_processing/natural_language_understanding/contextual_comprehension`.
Also exceptions were removed from feature validation so from now on only features that exist in the OASF instance are accepted.
Closes #224

feat(server, schema): simplified class names

---

server/lib/schema/json_schema.ex
server/lib/schema/validator.ex

This issue came up regarding the MCP feature class, where there is a `just_one` constraint on two attributes that are also `required` and that caused issues in the validators.
Fixes:
- in the validator api, if the `just_one` constraint was applied to required attributes, it would return an error if a required attribute was not present - it is fixed so the `just_one` constraint is stronger than `required`.
- in the Draft-07 JSON schema generator it is also implemented to respect the `just_one` and the `at_least_one` constraints
Fixes #235

fix(server): constraints in validator

---

schema/dictionary.json
server/lib/schema/generator.ex

Created new type which is a float between (and included) 0 and 1 to be used for the `priority` attribute with generator. Validation is also take care of due to the `range` constraints of the type.
Fixes #237

feat(server, schema): add unit_interval_t with generator

---

server/lib/schema.ex
server/lib/schema/json_schema.ex

There are `minimum`, `maximum` constraints in the json draft-07 schema, so this PR translates `range` from OASF types to these constraints in the generated schema.
Example schema for the `mcp_server_resource` object:
```json
{
"$defs": {},
"$id": "https://schema.oasf.outshift.com/schema/objects/mcp_server_resource",
"$schema": "http://json-schema.org/draft-07/schema#",
"additionalProperties": false,
"oneOf": [
{
"not": {
"required": ["uri"]
},
"required": ["uri_template"]
},
{
"not": {
"required": ["uri_template"]
},
"required": ["uri"]
}
],
"properties": {
"audience": {
"items": {
"enum": ["user", "assistant"],
"type": "string"
},
"title": "Audience",
"type": "array"
},
"description": {
"title": "Description",
"type": "string"
},
"mime_type": {
"title": "MIME Type",
"type": "string"
}, …
```

feat(server): add range to json schema generator

---

server/lib/schema/cache.ex
server/lib/schema/json_schema.ex
server/lib/schema/utils.ex
server/lib/schema/validator.ex

If an attribute is an enum object, now the validator tries to find the matching children for the input, if there are no matches, it returns an error.
Fixes #240

feat(server): validate enum objects

---

server/lib/schema/cache.ex
server/lib/schema/json_schema.ex
server/lib/schema/utils.ex
server/lib/schema/validator.ex
server/lib/schema_web/controllers/page_controller.ex
server/lib/schema_web/controllers/schema_controller.ex
server/lib/schema_web/templates/page/class.html.eex
server/lib/schema_web/templates/page/object.html.eex
server/lib/schema_web/views/page_view.ex
server/priv/static/css/components.css

Display children of a viewed class/object similar to how the Referenced by objects are displayed on the UI.
| Before | After |
|:------:|:-----:|
| <img width="1129" height="672" alt="Screenshot 2025-09-02 at 18 00 47" src="https://github.com/user-attachments/assets/ef91f1f6-d143-4071-ad89-36205d578be7" /> | <img width="1129" height="672" alt="Screenshot 2025-09-02 at 18 00 51" src="https://github.com/user-attachments/assets/475cc012-f819-40e8-8022-a116961b8c28" /> |
| <img width="1129" height="672" alt="Screenshot 2025-09-02 at 18 00 42" src="https://github.com/user-attachments/assets/81721a5c-5250-4882-9512-57aee24a06f4" /> | <img width="1129" height="672" alt="Screenshot 2025-09-02 at 18 00 56" src="https://github.com/user-attachments/assets/402b875a-6422-41c1-a4b2-9b06b95fb570" /> | …

feat(server): improve children object/class display

---

Taskfile.yml
proto/buf.yaml
proto/core/v1/object.proto

This PR adds a base object to OASF protos. The base object can be used to encode any OASF-defined object (such as record, module, etc) into a protobuf `Object` type. This is useful across the infra layer to explicitly differentiate between data coming from OASF and other places.
Goal: OASF defines objects and reserves types via some properties => upstream users leverage and provide functionality for certain objects
- To encode any object from OASF into JSON-based protobuf wire format
- Have explicit type to differentiate between OASF and non-OASF objects across gRPC APIs
- Ability to extract/convert a generic `Object` into any schema defined by OASF
**In OASF-SDK**
`DecodingService.DecodeRecord` to convert raw Object into a typed OASF-defined Record, and later to other types as well (e.g. …

feat: add base object to OASF

---

server/lib/schema/graph.ex
server/lib/schema/utils.ex
server/lib/schema_web/templates/page/class_graph.html.eex
server/lib/schema_web/templates/page/object_graph.html.eex

Graph mode now can handle class type and enum entities so it can render all related entities to an entity.
Closes #118

Fix: graph view
